// This is a mock database - in production, you'd want to use a real API
export const vehicleDatabase = {
	makes: [
		"Toyota",
		"Honda",
		"Ford",
		"Chevrolet",
		"BMW",
		"Mercedes-Benz",
		"Tesla",
		"Nissan",
		"Hyundai",
		"Kia",
		"Volkswagen",
		"Audi",
		"Lexus",
		"Mazda",
		"Subaru",
		"Porsche",
		"Jeep",
		"Ram",
		"GMC",
		"Acura",
	],
	models: {
		Toyota: [
			{ name: "Camry", mpg: 32 },
			{ name: "Corolla", mpg: 35 },
			{ name: "RAV4", mpg: 30 },
			{ name: "Prius", mpg: 58 },
			{ name: "Highlander", mpg: 24 },
			{ name: "4Runner", mpg: 17 },
			{ name: "Tacoma", mpg: 21 },
			{ name: "Tundra", mpg: 18 },
			{ name: "Sienna", mpg: 36 },
			{ name: "Venza", mpg: 39 },
		],
		Honda: [
			{ name: "Civic", mpg: 33 },
			{ name: "Accord", mpg: 32 },
			{ name: "CR-V", mpg: 29 },
			{ name: "Pilot", mpg: 23 },
			{ name: "HR-V", mpg: 30 },
			{ name: "Odyssey", mpg: 22 },
			{ name: "Ridgeline", mpg: 21 },
			{ name: "Passport", mpg: 21 },
			{ name: "Insight", mpg: 52 },
			{ name: "CR-V Hybrid", mpg: 38 },
		],
		Ford: [
			{ name: "F-150", mpg: 20 },
			{ name: "Mustang", mpg: 24 },
			{ name: "Explorer", mpg: 24 },
			{ name: "Escape", mpg: 28 },
			{ name: "Bronco", mpg: 20 },
			{ name: "Edge", mpg: 24 },
			{ name: "Ranger", mpg: 23 },
			{ name: "Expedition", mpg: 19 },
			{ name: "Maverick", mpg: 37 },
			{ name: "Mustang Mach-E", mpg: 100 },
		],
		Chevrolet: [
			{ name: "Malibu", mpg: 29 },
			{ name: "Silverado", mpg: 20 },
			{ name: "Equinox", mpg: 26 },
			{ name: "Traverse", mpg: 21 },
			{ name: "Tahoe", mpg: 18 },
			{ name: "Suburban", mpg: 17 },
			{ name: "Colorado", mpg: 22 },
			{ name: "Blazer", mpg: 24 },
			{ name: "Trax", mpg: 29 },
			{ name: "Bolt EV", mpg: 120 },
		],
		BMW: [
			{ name: "3 Series", mpg: 26 },
			{ name: "5 Series", mpg: 25 },
			{ name: "X3", mpg: 25 },
			{ name: "X5", mpg: 23 },
			{ name: "7 Series", mpg: 22 },
			{ name: "X1", mpg: 27 },
			{ name: "X7", mpg: 21 },
			{ name: "4 Series", mpg: 26 },
			{ name: "2 Series", mpg: 28 },
			{ name: "i4", mpg: 109 },
		],
		"Mercedes-Benz": [
			{ name: "C-Class", mpg: 25 },
			{ name: "E-Class", mpg: 23 },
			{ name: "GLC", mpg: 24 },
			{ name: "GLE", mpg: 21 },
			{ name: "S-Class", mpg: 22 },
			{ name: "A-Class", mpg: 28 },
			{ name: "GLA", mpg: 27 },
			{ name: "GLB", mpg: 26 },
			{ name: "GLS", mpg: 20 },
			{ name: "EQS", mpg: 97 },
		],
		Tesla: [
			{ name: "Model 3", mpg: 130 },
			{ name: "Model Y", mpg: 125 },
			{ name: "Model S", mpg: 120 },
			{ name: "Model X", mpg: 105 },
			{ name: "Cybertruck", mpg: 100 },
		],
		Nissan: [
			{ name: "Altima", mpg: 32 },
			{ name: "Rogue", mpg: 30 },
			{ name: "Sentra", mpg: 33 },
			{ name: "Maxima", mpg: 24 },
			{ name: "Pathfinder", mpg: 23 },
			{ name: "Murano", mpg: 23 },
			{ name: "Frontier", mpg: 20 },
			{ name: "Kicks", mpg: 33 },
			{ name: "Armada", mpg: 16 },
			{ name: "Leaf", mpg: 111 },
		],
		Hyundai: [
			{ name: "Elantra", mpg: 35 },
			{ name: "Sonata", mpg: 32 },
			{ name: "Tucson", mpg: 29 },
			{ name: "Santa Fe", mpg: 26 },
			{ name: "Palisade", mpg: 22 },
			{ name: "Kona", mpg: 30 },
			{ name: "Venue", mpg: 31 },
			{ name: "Accent", mpg: 36 },
			{ name: "Ioniq", mpg: 59 },
			{ name: "Ioniq 5", mpg: 114 },
		],
		Kia: [
			{ name: "Forte", mpg: 35 },
			{ name: "K5", mpg: 32 },
			{ name: "Sportage", mpg: 29 },
			{ name: "Telluride", mpg: 23 },
			{ name: "Sorento", mpg: 26 },
			{ name: "Soul", mpg: 31 },
			{ name: "Seltos", mpg: 31 },
			{ name: "Carnival", mpg: 22 },
			{ name: "Niro", mpg: 53 },
			{ name: "EV6", mpg: 117 },
		],
		Volkswagen: [
			{ name: "Jetta", mpg: 34 },
			{ name: "Passat", mpg: 28 },
			{ name: "Tiguan", mpg: 25 },
			{ name: "Atlas", mpg: 22 },
			{ name: "Taos", mpg: 31 },
			{ name: "Golf GTI", mpg: 28 },
			{ name: "Golf R", mpg: 26 },
			{ name: "ID.4", mpg: 107 },
			{ name: "Arteon", mpg: 25 },
			{ name: "Atlas Cross Sport", mpg: 22 },
		],
		Audi: [
			{ name: "A3", mpg: 32 },
			{ name: "A4", mpg: 28 },
			{ name: "A6", mpg: 26 },
			{ name: "Q3", mpg: 26 },
			{ name: "Q5", mpg: 25 },
			{ name: "Q7", mpg: 20 },
			{ name: "e-tron", mpg: 78 },
			{ name: "A5", mpg: 27 },
			{ name: "Q8", mpg: 19 },
			{ name: "RS e-tron GT", mpg: 82 },
		],
		Lexus: [
			{ name: "ES", mpg: 27 },
			{ name: "RX", mpg: 24 },
			{ name: "NX", mpg: 25 },
			{ name: "IS", mpg: 25 },
			{ name: "UX", mpg: 33 },
			{ name: "GX", mpg: 16 },
			{ name: "LS", mpg: 22 },
			{ name: "LC", mpg: 19 },
			{ name: "LX", mpg: 17 },
			{ name: "RC", mpg: 24 },
		],
		Mazda: [
			{ name: "Mazda3", mpg: 31 },
			{ name: "CX-5", mpg: 26 },
			{ name: "CX-30", mpg: 28 },
			{ name: "CX-9", mpg: 23 },
			{ name: "MX-5 Miata", mpg: 29 },
			{ name: "CX-50", mpg: 27 },
			{ name: "Mazda6", mpg: 29 },
			{ name: "CX-3", mpg: 31 },
			{ name: "MX-30", mpg: 92 },
			{ name: "CX-90", mpg: 25 },
		],
		Subaru: [
			{ name: "Outback", mpg: 29 },
			{ name: "Forester", mpg: 29 },
			{ name: "Crosstrek", mpg: 30 },
			{ name: "Impreza", mpg: 31 },
			{ name: "Legacy", mpg: 30 },
			{ name: "Ascent", mpg: 23 },
			{ name: "WRX", mpg: 22 },
			{ name: "BRZ", mpg: 25 },
			{ name: "Solterra", mpg: 94 },
			{ name: "Crosstrek Hybrid", mpg: 90 },
		],
		Porsche: [
			{ name: "911", mpg: 20 },
			{ name: "Cayenne", mpg: 20 },
			{ name: "Macan", mpg: 21 },
			{ name: "Panamera", mpg: 22 },
			{ name: "718 Cayman", mpg: 22 },
			{ name: "718 Boxster", mpg: 22 },
			{ name: "Taycan", mpg: 79 },
			{ name: "Cayenne E-Hybrid", mpg: 46 },
			{ name: "Panamera E-Hybrid", mpg: 52 },
			{ name: "Macan T", mpg: 21 },
		],
		Jeep: [
			{ name: "Grand Cherokee", mpg: 22 },
			{ name: "Cherokee", mpg: 25 },
			{ name: "Wrangler", mpg: 20 },
			{ name: "Compass", mpg: 25 },
			{ name: "Renegade", mpg: 27 },
			{ name: "Gladiator", mpg: 19 },
			{ name: "Wagoneer", mpg: 17 },
			{ name: "Grand Wagoneer", mpg: 15 },
			{ name: "Wrangler 4xe", mpg: 49 },
			{ name: "Grand Cherokee 4xe", mpg: 56 },
		],
		Ram: [
			{ name: "1500", mpg: 22 },
			{ name: "2500", mpg: 15 },
			{ name: "3500", mpg: 14 },
			{ name: "ProMaster", mpg: 16 },
			{ name: "ProMaster City", mpg: 24 },
			{ name: "1500 Classic", mpg: 20 },
			{ name: "1500 TRX", mpg: 12 },
			{ name: "1500 EcoDiesel", mpg: 26 },
			{ name: "2500 Power Wagon", mpg: 13 },
			{ name: "3500 Limited", mpg: 14 },
		],
		GMC: [
			{ name: "Sierra 1500", mpg: 20 },
			{ name: "Terrain", mpg: 27 },
			{ name: "Acadia", mpg: 24 },
			{ name: "Yukon", mpg: 18 },
			{ name: "Canyon", mpg: 22 },
			{ name: "Sierra 2500HD", mpg: 15 },
			{ name: "Sierra 3500HD", mpg: 14 },
			{ name: "Yukon XL", mpg: 17 },
			{ name: "Hummer EV", mpg: 47 },
			{ name: "Sierra EV", mpg: 92 },
		],
		Acura: [
			{ name: "TLX", mpg: 25 },
			{ name: "RDX", mpg: 24 },
			{ name: "MDX", mpg: 22 },
			{ name: "ILX", mpg: 28 },
			{ name: "NSX", mpg: 21 },
			{ name: "Integra", mpg: 32 },
			{ name: "TLX Type S", mpg: 21 },
			{ name: "MDX Type S", mpg: 19 },
			{ name: "RDX A-Spec", mpg: 23 },
			{ name: "Integra Type S", mpg: 28 },
		],
	},
	getMPG: function (make, model) {
		if (!this.models[make]) return null;
		const vehicle = this.models[make].find((m) => m.name === model);
		return vehicle ? vehicle.mpg : null;
	},
};
