import { Inter } from "next/font/google";
import "./globals.css";
import { APIProvider } from "../lib/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Gas Calculator",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<APIProvider apiKey={process.env.GOOGLE_MAPS_API_KEY}>
				<body className={inter.className}>{children}</body>
			</APIProvider>
		</html>
	);
}
